version: '3.4'

services:
  template:
    image: template
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 cryptocop-payments\payment-service.py "]
    ports:
      - 5678:5678
